export const INGREDIENT_CATEGORIES = [
  'Verduras y Hortalizas',
  'Frutas',
  'Carnes',
  'Pescados y Mariscos',
  'Lácteos y Huevos',
  'Legumbres y Cereales',
  'Pasta y Arroz',
  'Conservas y Preparados',
  'Condimentos y Especias',
  'Aceites y Vinagres',
  'Otros',
]

export const DEFAULT_INGREDIENTS = [
  // Verduras y Hortalizas
  { name: 'Cebolla', category: 'Verduras y Hortalizas' },
  { name: 'Ajo', category: 'Verduras y Hortalizas' },
  { name: 'Tomate', category: 'Verduras y Hortalizas' },
  { name: 'Pimiento rojo', category: 'Verduras y Hortalizas' },
  { name: 'Pimiento verde', category: 'Verduras y Hortalizas' },
  { name: 'Zanahoria', category: 'Verduras y Hortalizas' },
  { name: 'Patata', category: 'Verduras y Hortalizas' },
  { name: 'Calabacín', category: 'Verduras y Hortalizas' },
  { name: 'Berenjena', category: 'Verduras y Hortalizas' },
  { name: 'Espinacas', category: 'Verduras y Hortalizas' },
  { name: 'Lechuga', category: 'Verduras y Hortalizas' },
  { name: 'Pepino', category: 'Verduras y Hortalizas' },
  { name: 'Brócoli', category: 'Verduras y Hortalizas' },
  { name: 'Coliflor', category: 'Verduras y Hortalizas' },
  { name: 'Champiñones', category: 'Verduras y Hortalizas' },
  { name: 'Puerro', category: 'Verduras y Hortalizas' },
  { name: 'Apio', category: 'Verduras y Hortalizas' },
  { name: 'Cebolleta', category: 'Verduras y Hortalizas' },
  { name: 'Rúcula', category: 'Verduras y Hortalizas' },
  { name: 'Tomate cherry', category: 'Verduras y Hortalizas' },

  // Frutas
  { name: 'Limón', category: 'Frutas' },
  { name: 'Naranja', category: 'Frutas' },
  { name: 'Manzana', category: 'Frutas' },
  { name: 'Aguacate', category: 'Frutas' },
  { name: 'Plátano', category: 'Frutas' },

  // Carnes
  { name: 'Pollo (pechuga)', category: 'Carnes' },
  { name: 'Pollo (muslos)', category: 'Carnes' },
  { name: 'Carne picada (ternera)', category: 'Carnes' },
  { name: 'Carne picada (mixta)', category: 'Carnes' },
  { name: 'Ternera (filete)', category: 'Carnes' },
  { name: 'Cerdo (lomo)', category: 'Carnes' },
  { name: 'Cerdo (costillas)', category: 'Carnes' },
  { name: 'Jamón serrano', category: 'Carnes' },
  { name: 'Jamón cocido', category: 'Carnes' },
  { name: 'Bacon', category: 'Carnes' },
  { name: 'Chorizo', category: 'Carnes' },
  { name: 'Salchichas', category: 'Carnes' },
  { name: 'Cordero', category: 'Carnes' },

  // Pescados y Mariscos
  { name: 'Salmón', category: 'Pescados y Mariscos' },
  { name: 'Bacalao', category: 'Pescados y Mariscos' },
  { name: 'Merluza', category: 'Pescados y Mariscos' },
  { name: 'Atún fresco', category: 'Pescados y Mariscos' },
  { name: 'Gambas', category: 'Pescados y Mariscos' },
  { name: 'Mejillones', category: 'Pescados y Mariscos' },
  { name: 'Calamar', category: 'Pescados y Mariscos' },
  { name: 'Pulpo', category: 'Pescados y Mariscos' },
  { name: 'Lubina', category: 'Pescados y Mariscos' },
  { name: 'Dorada', category: 'Pescados y Mariscos' },

  // Lácteos y Huevos
  { name: 'Huevos', category: 'Lácteos y Huevos' },
  { name: 'Leche', category: 'Lácteos y Huevos' },
  { name: 'Nata para cocinar', category: 'Lácteos y Huevos' },
  { name: 'Mantequilla', category: 'Lácteos y Huevos' },
  { name: 'Queso rallado', category: 'Lácteos y Huevos' },
  { name: 'Queso fresco', category: 'Lácteos y Huevos' },
  { name: 'Queso manchego', category: 'Lácteos y Huevos' },
  { name: 'Mozzarella', category: 'Lácteos y Huevos' },
  { name: 'Yogur natural', category: 'Lácteos y Huevos' },
  { name: 'Queso crema', category: 'Lácteos y Huevos' },

  // Legumbres y Cereales
  { name: 'Garbanzos', category: 'Legumbres y Cereales' },
  { name: 'Lentejas', category: 'Legumbres y Cereales' },
  { name: 'Alubias blancas', category: 'Legumbres y Cereales' },
  { name: 'Alubias negras', category: 'Legumbres y Cereales' },
  { name: 'Pan rallado', category: 'Legumbres y Cereales' },
  { name: 'Harina de trigo', category: 'Legumbres y Cereales' },
  { name: 'Maíz (lata)', category: 'Legumbres y Cereales' },

  // Pasta y Arroz
  { name: 'Pasta (espaguetis)', category: 'Pasta y Arroz' },
  { name: 'Pasta (macarrones)', category: 'Pasta y Arroz' },
  { name: 'Pasta (penne)', category: 'Pasta y Arroz' },
  { name: 'Pasta (lasaña)', category: 'Pasta y Arroz' },
  { name: 'Arroz blanco', category: 'Pasta y Arroz' },
  { name: 'Arroz integral', category: 'Pasta y Arroz' },
  { name: 'Arroz bomba', category: 'Pasta y Arroz' },
  { name: 'Fideos', category: 'Pasta y Arroz' },

  // Conservas y Preparados
  { name: 'Tomate triturado (lata)', category: 'Conservas y Preparados' },
  { name: 'Tomate frito (bote)', category: 'Conservas y Preparados' },
  { name: 'Atún en lata', category: 'Conservas y Preparados' },
  { name: 'Sardinas en lata', category: 'Conservas y Preparados' },
  { name: 'Pesto (bote)', category: 'Conservas y Preparados' },
  { name: 'Caldo de pollo', category: 'Conservas y Preparados' },
  { name: 'Caldo de verduras', category: 'Conservas y Preparados' },
  { name: 'Caldo de pescado', category: 'Conservas y Preparados' },
  { name: 'Aceitunas', category: 'Conservas y Preparados' },
  { name: 'Alcaparras', category: 'Conservas y Preparados' },
  { name: 'Pimientos del piquillo', category: 'Conservas y Preparados' },

  // Condimentos y Especias
  { name: 'Sal', category: 'Condimentos y Especias' },
  { name: 'Pimienta negra', category: 'Condimentos y Especias' },
  { name: 'Pimentón dulce', category: 'Condimentos y Especias' },
  { name: 'Pimentón picante', category: 'Condimentos y Especias' },
  { name: 'Comino', category: 'Condimentos y Especias' },
  { name: 'Orégano', category: 'Condimentos y Especias' },
  { name: 'Tomillo', category: 'Condimentos y Especias' },
  { name: 'Romero', category: 'Condimentos y Especias' },
  { name: 'Laurel', category: 'Condimentos y Especias' },
  { name: 'Curry', category: 'Condimentos y Especias' },
  { name: 'Cúrcuma', category: 'Condimentos y Especias' },
  { name: 'Azafrán', category: 'Condimentos y Especias' },
  { name: 'Perejil', category: 'Condimentos y Especias' },
  { name: 'Albahaca fresca', category: 'Condimentos y Especias' },
  { name: 'Mostaza', category: 'Condimentos y Especias' },
  { name: 'Salsa de soja', category: 'Condimentos y Especias' },

  // Aceites y Vinagres
  { name: 'Aceite de oliva virgen extra', category: 'Aceites y Vinagres' },
  { name: 'Aceite de girasol', category: 'Aceites y Vinagres' },
  { name: 'Vinagre de vino', category: 'Aceites y Vinagres' },
  { name: 'Vinagre de manzana', category: 'Aceites y Vinagres' },
  { name: 'Vinagre balsámico', category: 'Aceites y Vinagres' },

  // Otros
  { name: 'Vino blanco', category: 'Otros' },
  { name: 'Vino tinto', category: 'Otros' },
  { name: 'Azúcar', category: 'Otros' },
  { name: 'Pan de molde', category: 'Otros' },
  { name: 'Pan', category: 'Otros' },
  { name: 'Nueces', category: 'Otros' },
  { name: 'Piñones', category: 'Otros' },
  { name: 'Pasas', category: 'Otros' },
]
